### ISSUE TITLE
Eth Mainnet shows 2 Dai by default If the user is not logged in to MetaMask or Nifty Wallet

### ISSUE THREAD

**Issue by SiddigZeidan** [poanetwork/bridge-ui#154]
**Issue**
Affected only on https://dai-bridge.poa.network/ not http://bridge.poa.net

ETH Mainnet shows my balance to be 2 Dai, however I am not logged in. It should show 0 Dai.
![image](https://user-images.githubusercontent.com/4807398/49186114-b1fe9a00-f331-11e8-8c34-7229e1e2a7f7.png)

**Comment by akolotov** [comment]
I saw similar issue during testing with other networks. Could it relate that some value from the browser storage are used?

**Comment by patitonar** [comment]
The issue is produced by making the call to get the token balance of the user even if user is not logged in, so we need to fix this. In this case, since we don't have the user account, it's making the call with an empty address. It turns out that `0x0000000000000000000000000000000000000000` address has a balance of [2 Dai](https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359?a=0x0000000000000000000000000000000000000000).
