### ISSUE TITLE
Optimize design to work on mobile

### ISSUE THREAD

**Issue by vikmeup** [poanetwork/bridge-ui#49]
![image 2018-04-29 16 50 45](https://user-images.githubusercontent.com/1641795/39412196-76708b58-4bcd-11e8-8486-65fb04ccfeac.jpg)

Browser: Trust Wallet.

**Comment by vikmeup** [comment]
Dup: https://github.com/poanetwork/bridge-ui/issues/47

**Comment by rstormsf** [comment]
actually lets keep this one

**Comment by dennis00010011b** [comment]
PR https://github.com/poanetwork/bridge-ui/pull/59
Fixed in portrait mode
Page non-scrollable and non-zoomed in landscape mode
Tested with Samsung Galaxy J7, Android 7.0

![screenshot_20180502-143508](https://user-images.githubusercontent.com/14067096/39550623-cb7cdd2c-4e16-11e8-88af-b52cec386cc0.png)
